function requestPostFun(myurl,myget,mydata,headersText="application/x-www-form-urlencoded" ){
	return new Promise((resolve,reject)=>{
		uni.request({
			url: myurl,
			method:myget||"get",
			data:mydata||{},
			header: {
				'content-type': headersText+";text/json; charset=utf-8"
			},
			success: (res) => {
				resolve(res)
			},
			fail:(err)=>{
				reject(err)
			}
		});
	})
}

import { serverUrl } from '@/utils/pathSetting/constPath.js'

export const sttp= params=>requestPostFun(serverUrl,'post',params);

export const requestPost= params=>requestPostFun(serverUrl,'post',params);
// this is a duplicate header and will be overridden by the content-type header generated by postman